package analyzers

import (
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/davisbuilds/envdiff/internal/model"
	"github.com/davisbuilds/envdiff/internal/order"
)

var requirednessOrder = map[string]int{
	"required":              0,
	"optional":              1,
	"optional_with_default": 2,
	"unknown":               3,
}

func GenerateExampleFile(scanResult model.RepoScanResult, annotate bool) map[string]any {
	contracts := []model.EnvVarContract{}
	for _, contract := range scanResult.Contracts {
		if containsString(contract.Status, "referenced") {
			contracts = append(contracts, contract)
		}
	}
	sort.SliceStable(contracts, func(left int, right int) bool {
		leftValue := contracts[left]
		rightValue := contracts[right]
		leftRank := requirednessRank(leftValue.Requiredness)
		rightRank := requirednessRank(rightValue.Requiredness)
		if leftRank != rightRank {
			return leftRank < rightRank
		}
		return leftValue.Name < rightValue.Name
	})

	lines := plainLines(contracts)
	if annotate {
		lines = annotatedLines(contracts)
	}
	generatedText := strings.Join(lines, "\n")
	if generatedText != "" {
		generatedText += "\n"
	}

	variables := make([]string, 0, len(contracts))
	for _, contract := range contracts {
		variables = append(variables, contract.Name)
	}

	return map[string]any{
		"annotate":       annotate,
		"generated_text": generatedText,
		"root_path":      scanResult.RootPath,
		"variable_count": len(contracts),
		"variables":      variables,
	}
}

func WriteGeneratedExample(path string, generatedText string) (string, error) {
	if err := os.WriteFile(path, []byte(generatedText), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func CheckGeneratedExample(
	rootPath string,
	generatedText string,
	output *string,
) (map[string]any, error) {
	targetPath := filepath.Join(rootPath, ".env.example")
	if output != nil {
		targetPath = *output
	}

	info, statErr := os.Stat(targetPath)
	exists := statErr == nil && info.Mode().IsRegular()

	var existing []byte
	if exists {
		read, err := os.ReadFile(targetPath)
		if err != nil {
			return nil, err
		}
		existing = read
	}
	matches := exists && string(existing) == generatedText

	return map[string]any{
		"exists":      exists,
		"matches":     matches,
		"target_path": targetPath,
	}, nil
}

func plainLines(contracts []model.EnvVarContract) []string {
	lines := make([]string, 0, len(contracts))
	for _, contract := range contracts {
		lines = append(lines, contract.Name+"=")
	}
	return lines
}

func annotatedLines(contracts []model.EnvVarContract) []string {
	lines := []string{"# Generated by envdiff. Review before committing."}
	currentGroup := ""

	for _, contract := range contracts {
		if contract.Requiredness != currentGroup {
			if len(lines) > 1 {
				lines = append(lines, "")
			}
			currentGroup = contract.Requiredness
			lines = append(lines, "# "+labelForRequiredness(contract.Requiredness))
		}

		defaultValues := defaultValuesForContract(contract)
		if len(defaultValues) > 0 {
			lines = append(lines, "# defaults in code: "+strings.Join(defaultValues, ", "))
		}
		lines = append(lines, contract.Name+"=")
	}

	return lines
}

func defaultValuesForContract(contract model.EnvVarContract) []string {
	values := []string{}
	seen := map[string]struct{}{}
	for _, usage := range contract.Usages {
		if usage.DefaultValue == nil {
			continue
		}
		if _, ok := seen[*usage.DefaultValue]; ok {
			continue
		}
		seen[*usage.DefaultValue] = struct{}{}
		values = append(values, *usage.DefaultValue)
	}
	return order.Strings(values)
}

func labelForRequiredness(requiredness string) string {
	switch requiredness {
	case "required":
		return "required"
	case "optional":
		return "optional"
	case "optional_with_default":
		return "optional with default"
	case "unknown":
		return "unknown"
	default:
		return requiredness
	}
}

func requirednessRank(requiredness string) int {
	if rank, ok := requirednessOrder[requiredness]; ok {
		return rank
	}
	return 99
}

func containsString(values []string, needle string) bool {
	for _, value := range values {
		if value == needle {
			return true
		}
	}
	return false
}
