package analyzers

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/davisbuilds/envdiff/internal/model"
	"github.com/davisbuilds/envdiff/internal/render"
	"github.com/davisbuilds/envdiff/internal/testutil"
)

func TestGenerateExampleFileEmitsReferencedContractsAsPlainDotenv(t *testing.T) {
	result := scanSimpleRepoForGenerate(t)
	generated := GenerateExampleFile(result, false)

	if generated["variable_count"] != 3 {
		t.Fatalf("variable_count = %v, want 3", generated["variable_count"])
	}
	variables := generated["variables"].([]string)
	wantVariables := []string{"DATABASE_URL", "REDIS_URL", "DEBUG"}
	for index := range wantVariables {
		if variables[index] != wantVariables[index] {
			t.Fatalf("variables = %v, want %v", variables, wantVariables)
		}
	}
	if generated["generated_text"] != "DATABASE_URL=\nREDIS_URL=\nDEBUG=\n" {
		t.Fatalf("generated_text = %q", generated["generated_text"])
	}
}

func TestGenerateExampleFileAnnotatesGroupsAndDefaults(t *testing.T) {
	result := scanSimpleRepoForGenerate(t)
	generated := GenerateExampleFile(result, true)
	text := generated["generated_text"].(string)

	for _, want := range []string{
		"# Generated by envdiff. Review before committing.",
		"# required",
		"# optional",
		"# optional with default",
		"# defaults in code: false",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("generated text missing %q:\n%s", want, text)
		}
	}
}

func TestGenerateExampleFileMatchesGoldens(t *testing.T) {
	assertGenerateMatchesGolden(t, false, "generate-simple-repo.json")
	assertGenerateMatchesGolden(t, true, "generate-simple-repo-annotated.json")
}

func TestCheckGeneratedExampleDetectsDriftAgainstDefaultExample(t *testing.T) {
	result := scanSimpleRepoForGenerate(t)
	generated := GenerateExampleFile(result, false)

	check, err := CheckGeneratedExample(result.RootPath, generated["generated_text"].(string), nil)
	if err != nil {
		t.Fatalf("check generated example: %v", err)
	}

	if check["exists"] != true {
		t.Fatalf("exists = %v, want true", check["exists"])
	}
	if check["matches"] != false {
		t.Fatalf("matches = %v, want false", check["matches"])
	}
}

func TestCheckGeneratedExampleTreatsDirectoryTargetAsMissing(t *testing.T) {
	result := scanSimpleRepoForGenerate(t)
	generated := GenerateExampleFile(result, false)

	dir := t.TempDir()
	check, err := CheckGeneratedExample(result.RootPath, generated["generated_text"].(string), &dir)
	if err != nil {
		t.Fatalf("check generated example: %v", err)
	}
	if check["exists"] != false {
		t.Fatalf("exists = %v, want false for a directory target", check["exists"])
	}
	if check["matches"] != false {
		t.Fatalf("matches = %v, want false for a directory target", check["matches"])
	}
}

func TestWriteGeneratedExampleWritesRequestedFile(t *testing.T) {
	outputPath := filepath.Join(t.TempDir(), ".env.example")

	written, err := WriteGeneratedExample(outputPath, "DATABASE_URL=\n")
	if err != nil {
		t.Fatalf("write generated example: %v", err)
	}
	content, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("read generated example: %v", err)
	}

	if written != outputPath {
		t.Fatalf("written path = %s, want %s", written, outputPath)
	}
	if string(content) != "DATABASE_URL=\n" {
		t.Fatalf("content = %q, want DATABASE_URL", string(content))
	}
}

func assertGenerateMatchesGolden(t *testing.T, annotate bool, golden string) {
	t.Helper()
	t.Chdir(testutil.RepoRoot(t))

	scanResult, err := ScanRepository("tests/fixtures/repos/simple_repo")
	if err != nil {
		t.Fatalf("scan repository: %v", err)
	}
	generated := GenerateExampleFile(scanResult, annotate)
	generated["output_path"] = nil
	generated["check"] = nil
	envelope := model.NewJsonEnvelope(
		"generate",
		map[string]any{
			"annotate": annotate,
			"check":    false,
			"output":   nil,
			"path":     "tests/fixtures/repos/simple_repo",
		},
		generated,
	)
	rendered, err := render.JSON(envelope)
	if err != nil {
		t.Fatalf("render JSON: %v", err)
	}

	got := testutil.DecodeJSON(t, []byte(rendered))
	got = testutil.NormalizeJSONValue(got, testutil.DefaultPathReplacements(t))
	want := testutil.LoadGoldenJSON(t, golden)
	testutil.AssertJSONEqual(t, got, want)
}

func scanSimpleRepoForGenerate(t *testing.T) model.RepoScanResult {
	t.Helper()

	result, err := ScanRepository(testutil.FixturePath(t, "repos", "simple_repo"))
	if err != nil {
		t.Fatalf("scan repository: %v", err)
	}
	return result
}
