from __future__ import annotations

import re
import runpy
import subprocess
import sys

import pytest
from typer.testing import CliRunner

import envdiff.cli as cli
from envdiff.cli import app

runner = CliRunner()

# Typer's Rich help splits styled spans with ANSI SGR codes in Python CLI tests.
_ANSI_SGR_RE = re.compile(r"\x1b\[[0-9;]*m")


def test_bin_launcher_help_smoke() -> None:
    result = subprocess.run(
        ["./envdiff", "--help"],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0
    output = _ANSI_SGR_RE.sub("", result.stdout)
    assert "Usage:" in output
    assert "compare" in output
    assert "doctor" in output


def test_cli_help_smoke() -> None:
    result = runner.invoke(app, ["--help"])

    assert result.exit_code == 0
    assert "compare" in result.stdout
    assert "generate" in result.stdout
    assert "matrix" in result.stdout
    assert "scan" in result.stdout
    assert "doctor" in result.stdout


def test_cli_compare_json_smoke() -> None:
    result = runner.invoke(
        app,
        [
            "compare",
            "tests/fixtures/compare/left.env",
            "tests/fixtures/compare/right.env",
            "--json",
        ],
    )

    assert result.exit_code == 0
    assert '"command": "compare"' in result.stdout
    assert '"missing_in_left"' in result.stdout


def test_cli_compare_human_smoke() -> None:
    result = runner.invoke(
        app,
        [
            "compare",
            "tests/fixtures/compare/left.env",
            "tests/fixtures/compare/right.env",
        ],
    )

    assert result.exit_code == 0
    assert "Missing in left" in result.stdout


def test_cli_scan_json_smoke() -> None:
    result = runner.invoke(
        app,
        ["scan", "tests/fixtures/repos/simple_repo", "--json"],
    )

    assert result.exit_code == 0
    assert '"command": "scan"' in result.stdout
    assert '"contracts"' in result.stdout


def test_cli_scan_human_smoke() -> None:
    result = runner.invoke(app, ["scan", "tests/fixtures/repos/simple_repo"])

    assert result.exit_code == 0
    assert "Contracts: 3" in result.stdout


def test_cli_matrix_json_smoke() -> None:
    result = runner.invoke(
        app,
        [
            "matrix",
            "tests/fixtures/matrix/a.env",
            "tests/fixtures/matrix/b.env",
            "tests/fixtures/matrix/c.env",
            "--json",
        ],
    )

    assert result.exit_code == 0
    assert '"command": "matrix"' in result.stdout
    assert '"inconsistent_variable_count"' in result.stdout


def test_cli_matrix_human_smoke() -> None:
    result = runner.invoke(
        app,
        [
            "matrix",
            "tests/fixtures/matrix/a.env",
            "tests/fixtures/matrix/b.env",
            "tests/fixtures/matrix/c.env",
        ],
    )

    assert result.exit_code == 0
    assert "Matrix files: 3" in result.stdout


def test_cli_matrix_rejects_single_path() -> None:
    result = runner.invoke(app, ["matrix", "tests/fixtures/matrix/a.env"])

    assert result.exit_code != 0
    assert "matrix requires at least two dotenv files" in result.output


def test_cli_generate_stdout_smoke() -> None:
    result = runner.invoke(
        app,
        ["generate", "tests/fixtures/repos/simple_repo"],
    )

    assert result.exit_code == 0
    assert result.stdout == "DATABASE_URL=\nREDIS_URL=\nDEBUG=\n"


def test_cli_generate_output_smoke(tmp_path) -> None:
    output_path = tmp_path / ".env.example"

    result = runner.invoke(
        app,
        [
            "generate",
            "tests/fixtures/repos/simple_repo",
            "--annotate",
            "--output",
            str(output_path),
        ],
    )

    assert result.exit_code == 0
    assert output_path.exists()
    assert "Generated 3 variables with annotations" in result.stdout
    assert "# Generated by envdiff. Review before committing." in output_path.read_text(
        encoding="utf-8"
    )


def test_cli_generate_json_smoke() -> None:
    result = runner.invoke(
        app,
        ["generate", "tests/fixtures/repos/simple_repo", "--json"],
    )

    assert result.exit_code == 0
    assert '"command": "generate"' in result.stdout
    assert '"generated_text"' in result.stdout


def test_cli_generate_check_detects_drift() -> None:
    result = runner.invoke(
        app,
        ["generate", "tests/fixtures/repos/simple_repo", "--check"],
    )

    assert result.exit_code == 2
    assert "drifted from" in result.stdout


def test_cli_generate_check_can_target_explicit_file(tmp_path) -> None:
    project = tmp_path / "project"
    app_dir = project / "app"
    app_dir.mkdir(parents=True)
    (project / ".env").write_text("DATABASE_URL=postgres://localhost/db\n", encoding="utf-8")
    (project / ".env.example").write_text("", encoding="utf-8")
    (app_dir / "main.py").write_text(
        'import os\n\ndatabase_url = os.environ["DATABASE_URL"]\n',
        encoding="utf-8",
    )
    target_path = tmp_path / "generated.env.example"
    target_path.write_text("DATABASE_URL=\n", encoding="utf-8")

    result = runner.invoke(
        app,
        ["generate", str(project), "--check", "--output", str(target_path)],
    )

    assert result.exit_code == 0
    assert "matches" in result.stdout


def test_cli_doctor_threshold_smoke() -> None:
    result = runner.invoke(
        app,
        ["doctor", "tests/fixtures/doctor/project", "--fail-on", "warning"],
    )

    assert result.exit_code == 2
    assert "ENV001" in result.stdout
    assert "Summary:" in result.stdout
    assert "Errors:" in result.stdout
    assert "Warnings:" in result.stdout
    assert "Infos:" in result.stdout


def test_cli_doctor_write_baseline_smoke(tmp_path) -> None:
    baseline_path = tmp_path / "doctor-baseline.json"

    result = runner.invoke(
        app,
        [
            "doctor",
            "tests/fixtures/doctor/project",
            "--write-baseline",
            str(baseline_path),
        ],
    )

    assert result.exit_code == 0
    assert baseline_path.exists()
    assert "Baseline written:" in result.stdout


def test_cli_doctor_baseline_suppresses_findings(tmp_path) -> None:
    baseline_path = tmp_path / "doctor-baseline.json"
    first = runner.invoke(
        app,
        [
            "doctor",
            "tests/fixtures/doctor/project",
            "--write-baseline",
            str(baseline_path),
        ],
    )
    assert first.exit_code == 0

    second = runner.invoke(
        app,
        [
            "doctor",
            "tests/fixtures/doctor/project",
            "--baseline",
            str(baseline_path),
            "--fail-on",
            "warning",
        ],
    )

    assert second.exit_code == 0
    assert "Findings: 0" in second.stdout
    assert "No active findings." in second.stdout


def test_cli_doctor_json_reports_suppression_metadata(tmp_path) -> None:
    baseline_path = tmp_path / "doctor-baseline.json"
    ignore_path = tmp_path / ".envdiffignore"
    write_result = runner.invoke(
        app,
        [
            "doctor",
            "tests/fixtures/doctor/project",
            "--write-baseline",
            str(baseline_path),
        ],
    )
    assert write_result.exit_code == 0
    ignore_path.write_text("missing:does-not-match:VALUE\n", encoding="utf-8")

    result = runner.invoke(
        app,
        [
            "doctor",
            "tests/fixtures/doctor/project",
            "--baseline",
            str(baseline_path),
            "--ignore-file",
            str(ignore_path),
            "--json",
        ],
    )

    assert result.exit_code == 0
    assert '"command": "doctor"' in result.stdout
    assert '"baseline_entries"' in result.stdout
    assert '"suppressed_findings"' in result.stdout


def test_cli_doctor_uses_default_ignore_file(tmp_path) -> None:
    project = tmp_path / "project"
    app_dir = project / "app"
    app_dir.mkdir(parents=True)
    (project / ".env").write_text("", encoding="utf-8")
    (project / ".env.example").write_text("API_KEY=\n", encoding="utf-8")
    (project / ".envdiffignore").write_text(
        f"missing:{app_dir / 'main.py'}:API_KEY\n",
        encoding="utf-8",
    )
    (app_dir / "main.py").write_text('import os\nos.environ["API_KEY"]\n', encoding="utf-8")

    result = runner.invoke(app, ["doctor", str(project), "--json"])

    assert result.exit_code == 0
    assert '"ignore_file":' in result.stdout
    assert '"error": 0' in result.stdout


def test_cli_doctor_fail_on_info_exits_for_info_only_findings(tmp_path) -> None:
    project = tmp_path / "project"
    project.mkdir()
    (project / ".env").write_text("STALE=value\n", encoding="utf-8")

    result = runner.invoke(app, ["doctor", str(project), "--fail-on", "info"])

    assert result.exit_code == 2
    assert "ENV003 STALE" in result.stdout


def test_cli_generate_check_json_includes_check_result(tmp_path) -> None:
    project = tmp_path / "project"
    app_dir = project / "app"
    app_dir.mkdir(parents=True)
    (project / ".env").write_text("DATABASE_URL=postgres://localhost/db\n", encoding="utf-8")
    (project / ".env.example").write_text("", encoding="utf-8")
    (app_dir / "main.py").write_text(
        'import os\n\ndatabase_url = os.environ["DATABASE_URL"]\n',
        encoding="utf-8",
    )
    target_path = tmp_path / "generated.env.example"
    target_path.write_text("DATABASE_URL=\n", encoding="utf-8")

    result = runner.invoke(
        app,
        ["generate", str(project), "--check", "--output", str(target_path), "--json"],
    )

    assert result.exit_code == 0
    assert '"check": {' in result.stdout
    assert '"matches": true' in result.stdout


def test_should_fail_rejects_unknown_threshold() -> None:
    result = runner.invoke(
        app,
        ["doctor", "tests/fixtures/doctor/project", "--fail-on", "debug"],
    )

    assert result.exit_code != 0
    assert "fail-on must be one of" in result.output


def test_main_invokes_typer_app(monkeypatch) -> None:
    calls = []

    monkeypatch.setattr(cli, "app", lambda: calls.append("called"))

    cli.main()

    assert calls == ["called"]


def test_module_entrypoint_invokes_main(monkeypatch) -> None:
    monkeypatch.setattr(sys, "argv", ["envdiff", "--help"])

    with pytest.warns(RuntimeWarning, match="'envdiff.cli' found in sys.modules"):
        try:
            runpy.run_module("envdiff.cli", run_name="__main__")
        except SystemExit as exc:
            assert exc.code == 0
