from __future__ import annotations

import subprocess

from typer.testing import CliRunner

from src.cli import app

runner = CliRunner()


def test_bin_launcher_help_smoke() -> None:
    result = subprocess.run(
        ["./envdiff", "--help"],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0
    assert "Usage: envdiff" in result.stdout


def test_cli_help_smoke() -> None:
    result = runner.invoke(app, ["--help"])

    assert result.exit_code == 0
    assert "compare" in result.stdout
    assert "generate" in result.stdout
    assert "matrix" in result.stdout
    assert "scan" in result.stdout
    assert "doctor" in result.stdout


def test_cli_compare_json_smoke() -> None:
    result = runner.invoke(
        app,
        [
            "compare",
            "tests/fixtures/compare/left.env",
            "tests/fixtures/compare/right.env",
            "--json",
        ],
    )

    assert result.exit_code == 0
    assert '"command": "compare"' in result.stdout
    assert '"missing_in_left"' in result.stdout


def test_cli_scan_json_smoke() -> None:
    result = runner.invoke(
        app,
        ["scan", "tests/fixtures/repos/simple_repo", "--json"],
    )

    assert result.exit_code == 0
    assert '"command": "scan"' in result.stdout
    assert '"contracts"' in result.stdout


def test_cli_matrix_json_smoke() -> None:
    result = runner.invoke(
        app,
        [
            "matrix",
            "tests/fixtures/matrix/a.env",
            "tests/fixtures/matrix/b.env",
            "tests/fixtures/matrix/c.env",
            "--json",
        ],
    )

    assert result.exit_code == 0
    assert '"command": "matrix"' in result.stdout
    assert '"inconsistent_variable_count"' in result.stdout


def test_cli_generate_stdout_smoke() -> None:
    result = runner.invoke(
        app,
        ["generate", "tests/fixtures/repos/simple_repo"],
    )

    assert result.exit_code == 0
    assert result.stdout == "DATABASE_URL=\nREDIS_URL=\nDEBUG=\n"


def test_cli_generate_output_smoke(tmp_path) -> None:
    output_path = tmp_path / ".env.example"

    result = runner.invoke(
        app,
        [
            "generate",
            "tests/fixtures/repos/simple_repo",
            "--annotate",
            "--output",
            str(output_path),
        ],
    )

    assert result.exit_code == 0
    assert output_path.exists()
    assert "Generated 3 variables with annotations" in result.stdout
    assert "# Generated by envdiff. Review before committing." in output_path.read_text(
        encoding="utf-8"
    )


def test_cli_generate_json_smoke() -> None:
    result = runner.invoke(
        app,
        ["generate", "tests/fixtures/repos/simple_repo", "--json"],
    )

    assert result.exit_code == 0
    assert '"command": "generate"' in result.stdout
    assert '"generated_text"' in result.stdout


def test_cli_generate_check_detects_drift() -> None:
    result = runner.invoke(
        app,
        ["generate", "tests/fixtures/repos/simple_repo", "--check"],
    )

    assert result.exit_code == 2
    assert "drifted from" in result.stdout


def test_cli_generate_check_can_target_explicit_file(tmp_path) -> None:
    project = tmp_path / "project"
    app_dir = project / "app"
    app_dir.mkdir(parents=True)
    (project / ".env").write_text("DATABASE_URL=postgres://localhost/db\n", encoding="utf-8")
    (project / ".env.example").write_text("", encoding="utf-8")
    (app_dir / "main.py").write_text(
        'import os\n\ndatabase_url = os.environ["DATABASE_URL"]\n',
        encoding="utf-8",
    )
    target_path = tmp_path / "generated.env.example"
    target_path.write_text("DATABASE_URL=\n", encoding="utf-8")

    result = runner.invoke(
        app,
        ["generate", str(project), "--check", "--output", str(target_path)],
    )

    assert result.exit_code == 0
    assert "matches" in result.stdout


def test_cli_doctor_threshold_smoke() -> None:
    result = runner.invoke(
        app,
        ["doctor", "tests/fixtures/doctor/project", "--fail-on", "warning"],
    )

    assert result.exit_code == 2
    assert "ENV001" in result.stdout
    assert "Summary:" in result.stdout
    assert "Errors:" in result.stdout
    assert "Warnings:" in result.stdout
    assert "Infos:" in result.stdout


def test_cli_doctor_write_baseline_smoke(tmp_path) -> None:
    baseline_path = tmp_path / "doctor-baseline.json"

    result = runner.invoke(
        app,
        [
            "doctor",
            "tests/fixtures/doctor/project",
            "--write-baseline",
            str(baseline_path),
        ],
    )

    assert result.exit_code == 0
    assert baseline_path.exists()
    assert "Baseline written:" in result.stdout


def test_cli_doctor_baseline_suppresses_findings(tmp_path) -> None:
    baseline_path = tmp_path / "doctor-baseline.json"
    first = runner.invoke(
        app,
        [
            "doctor",
            "tests/fixtures/doctor/project",
            "--write-baseline",
            str(baseline_path),
        ],
    )
    assert first.exit_code == 0

    second = runner.invoke(
        app,
        [
            "doctor",
            "tests/fixtures/doctor/project",
            "--baseline",
            str(baseline_path),
            "--fail-on",
            "warning",
        ],
    )

    assert second.exit_code == 0
    assert "Findings: 0" in second.stdout
    assert "No active findings." in second.stdout
