from __future__ import annotations

from envdiff.analyzers.generate import generate_example_file
from envdiff.analyzers.scan import scan_repository


def test_generate_emits_referenced_contract_as_plain_dotenv() -> None:
    result = generate_example_file(
        scan_repository("tests/fixtures/repos/simple_repo"),
    )

    assert result["variable_count"] == 3
    assert result["variables"] == ["DATABASE_URL", "REDIS_URL", "DEBUG"]
    assert result["generated_text"] == "DATABASE_URL=\nREDIS_URL=\nDEBUG=\n"


def test_generate_annotate_groups_by_requiredness_and_defaults() -> None:
    result = generate_example_file(
        scan_repository("tests/fixtures/repos/simple_repo"),
        annotate=True,
    )

    assert "# Generated by envdiff. Review before committing." in result["generated_text"]
    assert "# required" in result["generated_text"]
    assert "# optional" in result["generated_text"]
    assert "# optional with default" in result["generated_text"]
    assert "# defaults in code: false" in result["generated_text"]
