from __future__ import annotations

from pathlib import Path

from envdiff.models import EnvVarContract, RepoScanResult

REQUIREDNESS_ORDER = {
    "required": 0,
    "optional": 1,
    "optional_with_default": 2,
    "unknown": 3,
}


def generate_example_file(
    scan_result: RepoScanResult,
    *,
    annotate: bool = False,
) -> dict[str, object]:
    contracts = [contract for contract in scan_result.contracts if "referenced" in contract.status]
    ordered_contracts = sorted(
        contracts,
        key=lambda contract: (
            REQUIREDNESS_ORDER.get(contract.requiredness, 99),
            contract.name,
        ),
    )

    lines = _annotated_lines(ordered_contracts) if annotate else _plain_lines(ordered_contracts)
    generated_text = "\n".join(lines)
    if generated_text:
        generated_text += "\n"

    return {
        "root_path": scan_result.root_path,
        "annotate": annotate,
        "variable_count": len(ordered_contracts),
        "variables": [contract.name for contract in ordered_contracts],
        "generated_text": generated_text,
    }


def write_generated_example(path: str | Path, generated_text: str) -> str:
    output_path = Path(path)
    output_path.write_text(generated_text, encoding="utf-8")
    return str(output_path)


def check_generated_example(
    root_path: str | Path,
    generated_text: str,
    *,
    output: str | Path | None = None,
) -> dict[str, object]:
    target_path = Path(output) if output else Path(root_path) / ".env.example"
    exists = target_path.is_file()
    existing_text = target_path.read_text(encoding="utf-8") if exists else None
    matches = existing_text == generated_text

    return {
        "target_path": str(target_path),
        "exists": exists,
        "matches": matches,
    }


def _plain_lines(contracts: list[EnvVarContract]) -> list[str]:
    return [f"{contract.name}=" for contract in contracts]


def _annotated_lines(contracts: list[EnvVarContract]) -> list[str]:
    lines = ["# Generated by envdiff. Review before committing."]
    current_group = None

    for contract in contracts:
        if contract.requiredness != current_group:
            if len(lines) > 1:
                lines.append("")
            current_group = contract.requiredness
            lines.append(f"# {_label_for_requiredness(contract.requiredness)}")

        default_values = sorted(
            {usage.default_value for usage in contract.usages if usage.default_value is not None}
        )
        if default_values:
            lines.append(f"# defaults in code: {', '.join(default_values)}")
        lines.append(f"{contract.name}=")

    return lines


def _label_for_requiredness(requiredness: str) -> str:
    labels = {
        "required": "required",
        "optional": "optional",
        "optional_with_default": "optional with default",
        "unknown": "unknown",
    }
    return labels.get(requiredness, requiredness)
